### ISSUE TITLE
Curse addons without gameversion cannot be found via Catalog

### ISSUE THREAD

**Issue by mlablah** [ajour/ajour-catalog#13]
Certain addon releases do not present a "gameversion" in the api response. I do not know if this is a bug in curseforge, by design or an oversight on the part of the addon authors when uploading to curseforge.

Either way, it results in an addon that cannot be found via Ajour's Catalog tab. Looking in the curse.json there are records for the addons, but they are listed as having no flavors (and no gameVersions) and therefore it's not possible to perform a search in Ajour that would return it. 

I think this is because curse.sh does a grouping per gameversion to get unique flavors and gameversions: https://github.com/casperstorm/ajour-catalog/blob/master/curse.sh#L32-L39

Examples include:
Angrier World Quests: https://addons-ecs.forgesvc.net/api/v2/addon/426990
Stay Collapsed: https://addons-ecs.forgesvc.net/api/v2/addon/430968

API response: 
![image](https://user-images.githubusercontent.com/68285419/103460859-04cd8b80-4d1a-11eb-98eb-3564cb591e39.png)
Notice gameVersion is [] but gameVersionFlavor has a value: wow_retail.

**Comment by casperstorm** [comment]
@petergp i am wondering if we can do some changes 🤔
I think issue here is that `game_version` is null but `game_flavor` is `wow_retail` currently we then say welp, we don't have `game_version` so we map the whole thing to nothing.

So the solution could be, in the case `game_version` is null (or empty) map it to `Unknown`, `-` or similar.

**Comment by petergam** [comment]
@casperstorm Makes sense.  I'll take a look at implementing this.
