### ISSUE TITLE
tukui - add two single addons.

### ISSUE THREAD

**Issue by casperstorm** [ajour/ajour-catalog#6]
So it seems like the two MAIN addons (Tuk and Elv) is actually not in API call. There are four version of them:

1. Tukui Retail
2. Tukui Classic
3. Elvui Retail
4. Elvui Classic

Both classic versions is in the call we [use](https://github.com/casperstorm/ajour-catalog/blob/master/tukui.sh#L8-L10). So we are missing **Tukui Retail** and **Elvui Retail**. These are actually the two "main" addons where all the others are addons to these.

We can get them from these two sites:

Elvui Retail: https://www.tukui.org/api.php?ui=elvui
Tukui Retail: https://www.tukui.org/api.php?ui=tukui

I've added a `jq` for Tukui I think will work: 
```bash
{id: .id, dateReleased: .lastupdate, websiteUrl: .web_url, name: .name, summary: "", numberOfDownloads: .downloads, categories: [.category], flavors: ["wow_retail"], gameVersions: [{game_version: .patch, flavor: "wow_retail"}], source: "tukui"}
```

We should add these to `tukui.json` if possible.

**Comment by casperstorm** [comment]
@petergp Is this something you would like to look at somepoint? No rush.

**Comment by petergam** [comment]
Yes that sounds pretty straight forward

**Comment by casperstorm** [comment]
We can use this summary from their site, and just hardcode it.

Tuk
```
MINIMALISTIC AND LIGHTWEIGHT WORLD OF WARCRAFT USER INTERFACE!
```

Elv
```
A USER INTERFACE DESIGNED AROUND USER-FRIENDLINESS WITH EXTRA FEATURES THAT ARE NOT INCLUDED IN THE STANDARD UI.
```
